-- Revenue Autopilot — raw CDP export mirrors
-- Each table preserves a CSV from Woki 1:1 so downstream logic can be built
-- on full-fidelity data. No FKs to app tables: the CDP export does not carry
-- a cdp_visit ↔ cdp_guest_partner link (known gap).

create table if not exists cdp_visits (
  visit_id text primary key,
  tenant text,
  partner_id text,
  visit_type text,
  party_size int,
  party_size_seated int,
  sector_name text,
  channel text,
  platform text,
  state text,
  visit_outcome text,
  guest_comment text,
  venue_comment text,
  tags jsonb,
  arrived_at timestamptz,
  departed_at timestamptz,
  score numeric,
  review_food_rating numeric,
  review_service_rating numeric,
  review_ambience_rating numeric,
  review_overall_rating numeric,
  review_comment text,
  review_venue_reply text,
  review_tags jsonb,
  review_visit_type text,
  review_likes_count int,
  review_dislikes_count int,
  discount_percentage numeric,
  visited_at timestamptz,
  has_guarantee boolean,
  guarantee_amount numeric,
  cancelled_by text,
  cancelled_at timestamptz,
  confirmed_at timestamptz,
  accepted_at timestamptz,
  no_show_at timestamptz,
  rejected_at timestamptz,
  shift_id text,
  source_state text
);

create index if not exists idx_cdp_visits_visited_at on cdp_visits(visited_at);
create index if not exists idx_cdp_visits_partner_id on cdp_visits(partner_id);
create index if not exists idx_cdp_visits_state on cdp_visits(state);
create index if not exists idx_cdp_visits_outcome on cdp_visits(visit_outcome);

create table if not exists cdp_guest_partners (
  guest_partner_id text primary key,
  tenant text,
  partner_id text,
  brand_id text,
  guest_name text,
  guest_email text,
  guest_language text,
  location_name text,
  location_categories jsonb,
  location_city text,
  partner_tags jsonb,
  special_relationship text,
  food_restrictions text,
  total_visits int,
  total_walkins int,
  total_bookings int,
  total_pending int,
  total_no_shows int,
  total_cancellations int,
  total_rejected int,
  no_show_rate numeric,
  cancellation_rate numeric,
  rejection_rate numeric,
  booking_conversion_rate numeric,
  confirmation_rate numeric,
  guarantee_insights jsonb,
  cancellation_insights jsonb,
  review_insights jsonb,
  channel_insights jsonb,
  waitlist_insights jsonb,
  preferred_visit_context text,
  total_lead_time_minutes numeric,
  completed_booking_count int,
  total_score numeric,
  scored_visit_count int,
  last_score numeric,
  last_scored_at timestamptz,
  last_lead_time_minutes numeric,
  last_review_rating numeric,
  total_party_size numeric,
  party_size_count int,
  total_seated_guests numeric,
  seated_visit_count int,
  total_guests_brought int,
  is_favorite boolean,
  preferred_visit_type text,
  preferred_platform text,
  booking_tags jsonb,
  preferred_shift text,
  preferred_day_of_week text,
  preferred_sector text,
  preferred_channel text,
  first_booking_channel text,
  direct_booking_rate numeric,
  direct_booking_count int,
  total_venue_notes int,
  is_banned boolean,
  first_visit_at timestamptz,
  last_visit_at timestamptz,
  days_since_last int,
  total_days_between_visits numeric,
  visit_gap_count int,
  next_visit_at timestamptz,
  days_until_next int,
  calculated_at timestamptz,
  review_experience_tags jsonb,
  avg_discount_percentage numeric,
  total_discounted_visits int,
  last_booking_channel text,
  is_highlighted boolean,
  source text
);

create index if not exists idx_cdp_gp_total_visits on cdp_guest_partners(total_visits);
create index if not exists idx_cdp_gp_days_since_last on cdp_guest_partners(days_since_last);
create index if not exists idx_cdp_gp_last_visit_at on cdp_guest_partners(last_visit_at);
create index if not exists idx_cdp_gp_email on cdp_guest_partners(guest_email);

create table if not exists cdp_guest_unified (
  guest_id text primary key,
  name text,
  primary_email text,
  total_tenants int,
  total_locations int,
  total_visits_global int,
  total_walkins_global int,
  total_bookings_global int,
  total_no_shows_global int,
  total_cancellations_global int,
  total_rejected_global int,
  total_referrals_made int,
  global_no_show_rate numeric,
  total_guests_brought int,
  platform_score numeric,
  guarantee_insights jsonb,
  cancellation_insights jsonb,
  review_insights jsonb,
  total_lead_time_minutes numeric,
  completed_booking_count int,
  total_score numeric,
  scored_visit_count int,
  last_score numeric,
  last_scored_at timestamptz,
  last_lead_time_minutes numeric,
  total_party_size numeric,
  party_size_count int,
  total_seated_guests numeric,
  seated_visit_count int,
  total_days_between_visits numeric,
  visit_gap_count int,
  total_venue_notes_global int,
  favorite_partner_id text,
  favorite_location_name text,
  preferred_visit_type text,
  preferred_shift text,
  preferred_day_of_week text,
  channel_insights jsonb,
  food_restrictions text,
  is_banned boolean,
  cuisine_preferences jsonb,
  visited_cities jsonb,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  days_since_last int,
  next_visit_at timestamptz,
  days_until_next int,
  next_visit_location_name text,
  calculated_at timestamptz,
  guest_language text,
  global_cancellation_rate numeric,
  global_rejection_rate numeric,
  global_booking_conversion_rate numeric,
  global_confirmation_rate numeric,
  waitlist_insights jsonb,
  preferred_platform text,
  preferred_channel text,
  total_pending_global int,
  last_review_rating numeric,
  review_experience_tags jsonb,
  avg_discount_percentage numeric,
  total_discounted_visits_global int,
  source text
);

create index if not exists idx_cdp_gu_email on cdp_guest_unified(primary_email);
create index if not exists idx_cdp_gu_last_seen on cdp_guest_unified(last_seen_at);
